[toolchain]
solana_version = "3.1.6"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
paperclip_protocol = "Fehg9nbFCRnrZAuaW6tiqnegbHpHgizV9bvakhAWix6v"

[programs.localnet]
paperclip_protocol = "29kNcBm1gE7xn3ksX2VTQmwoJR8y8vxPhbF9MZYwjLgo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
